# K Nearest Neighbors Classification (K-NN)

In [ ]:
# Importing Libraries and Data Set
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mp
import seaborn as sns
iris = sns.load_dataset('iris')

## Defining new X and Y

In [ ]:
# Defining new X and Y
x = iris.iloc[:, :-1].values
y = iris.iloc[:, -1].values

## Splitting the Data Set into the Training and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

## Feature Scalling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Training the K-NN Model on the Training Set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, algorithm = 'auto', metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

## Predicting a Particular Result

In [ ]:
print(classifier.predict(sc.transform([[5,2,1,0.9]])))

## Predicting the Results of Test Set

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Confusion Matrix and Accuracy

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 10  1]
 [ 0  1 13]]


0.9473684210526315