# Logistic Regression Classification

## Importing Libraries & Data Set

In [6]:
# Importing Libraries and Data Set
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
iris = sns.load_dataset('iris')

## Defining X and Y values and Splitting the Data Set into Training and Test Sets

In [4]:
# Defining new X and Y
x = iris.iloc[:, :-1].values
y = iris.iloc[:, -1].values

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)

## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Training the Logistic Regression Model on the Training Set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=1)
classifier.fit(x_train,y_train)

## Predicting a particular Result

In [ ]:
print(classifier.predict(sc.transform([[15,1.7,5,2]])))

## Predicting the Test Set Results

In [ ]:
y_predict = classifier.predict(x_test)
print(np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1))

## Confusion Matrix and Accuracy

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)
accuracy_score(y_test,y_predict)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


0.9736842105263158